on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.17.x', '1.18.x', '1.19.x' ]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.57.2
      - name: Run unit tests
        run: go test ./...
